# -*- mode: python ; coding: utf-8 -*-
# ProxyForce v2.1 - ONEDIR build spec
# Output: dist\ProxyForce\  (folder — zip and distribute the whole folder)
#
# WHY ONEDIR (not onefile):
# PyInstaller onefile self-extracts all bundled files (including the bundled
# sing-box.exe and libcronet.dll) to a %TEMP%\MEI* directory at every launch.
# Windows Defender's ML engine (Sabsik.TE.A!ml) flags this as "dropper" behaviour:
# an unsigned exe unpacking a 43 MB PE + large native DLL to disk looks exactly
# like a dropper/trojan. The detection is a false positive but Defender quarantines
# the exe before it can run.
#
# ONEDIR keeps sing-box.exe and libcronet.dll in dist\ProxyForce\_internal\singbox\
# on disk from the moment the user extracts the zip. No runtime self-extraction
# happens; Defender sees a normal folder of files, not a dropper. This eliminates
# the single largest ML trigger.
#
# Additional hardening (vs v2.0.x):
#   • Version resource + company/product metadata embedded via version_info.txt
#     (unsigned bare PEs with no metadata score higher on suspicion).
#   • Application icon embedded (assets\proxyforce.ico, generated by tools\make_assets.py).
#   • PyInstaller bootloader rebuilt from source in CI so the exe stub doesn't carry
#     the identical hash of the PyInstaller pip wheel's prebuilt bootloader.
#   • asInvoker manifest + ShellExecuteW self-elevation retained from v2.0.2
#     (requireAdministrator manifests trigger Defender's aggressive scan path).
#
# Distribution: dist\ProxyForce\ is zipped by CI and published as the release asset.
# Users: download zip → extract anywhere → run ProxyForce.exe → approve UAC.
# The folder must stay together (exe needs _internal\ sibling).
#
# _find_singbox_exe() in core/singbox_controller.py already resolves the onedir
# layout: candidate #2 is <exedir>\_internal\singbox\sing-box.exe — no code change.
#
# Build command:
#   python tools/make_assets.py          # generate assets/proxyforce.ico
#   python -m PyInstaller proxyforce_onefile.spec --clean --noconfirm

import os
from PyInstaller.utils.hooks import collect_data_files

block_cipher = None

# customtkinter ships theme JSON + image assets.
_ctk_data = collect_data_files("customtkinter")

# The packet engine: sing-box binary + libcronet.dll + supporting files.
_singbox_data = [('vendor/singbox/*', 'singbox')]
if not os.path.isfile(os.path.join('vendor', 'singbox', 'sing-box.exe')):
    print("\n[!] vendor/singbox/sing-box.exe is missing — fetch it before building.\n")

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        # sing-box binary + supporting files (placed in _internal\singbox\ in onedir).
    ] + _singbox_data + _ctk_data,
    hiddenimports=[
        # core modules (imported lazily in engine control path)
        'core.singbox_controller',
        'core.config_store',
        'core.system_proxy',
        # auto-updater (lazily imported in main.py for --apply-update)
        'core.updater',
        'core._version',
        'core._ed25519',
        'hashlib',
        'zipfile',
        'urllib.parse',
        'datetime',
        # GUI framework
        'customtkinter',
        # System tray
        'pystray',
        'pystray._win32',
        # Pillow (tray icon + CTk image support)
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        # Clash-API stats client
        'urllib.request',
        'http.client',
        'email',
        # Windows ctypes/registry (used by config_store + Job Object)
        'winreg',
        'ctypes',
        'ctypes.wintypes',
        # stdlib used at runtime
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'queue',
        'ipaddress',
        'base64',
        'select',
        'socket',
        'threading',
        'logging',
        'subprocess',
        'shutil',
        'importlib.util',
        'math',
        're',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Trim fat — none of these are used.
        'matplotlib', 'numpy', 'scipy', 'pandas',
        'html', 'xml',
        'unittest', 'pydoc', 'doctest',
        # pywin32 removed (no Windows service in v2.0)
        'win32service', 'win32serviceutil', 'win32event',
        'servicemanager', 'win32timezone', 'pywintypes',
        'pythoncom', 'win32api',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ── UAC manifest: asInvoker (self-elevation via ShellExecuteW in main.py) ────
# WHY asInvoker (not requireAdministrator):
# On Windows 10, embedding "requireAdministrator" in the manifest causes Defender
# to apply its most aggressive real-time scanning to unsigned exes from the internet.
# Solution: ship the exe as asInvoker, then main.py calls ShellExecuteW("runas")
# to re-launch itself elevated. The UAC prompt still appears; just triggered by code.
_GUI_MANIFEST = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- Windows 10 / 11 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
    </application>
  </compatibility>
</assembly>'''

# ── ONEDIR: exe stub + all assets in dist\ProxyForce\ ───────────────────────
exe = EXE(
    pyz,
    a.scripts,
    [],                      # binaries/datas go into _internal\ via COLLECT, not the stub
    exclude_binaries=True,   # onedir mode
    name='ProxyForce',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,               # OFF: UPX-packed exes trigger AV/SmartScreen.
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=False,         # Self-elevation via ShellExecuteW in main.py
    manifest=_GUI_MANIFEST,
    icon='assets/proxyforce.ico',   # generated by: python tools/make_assets.py
    version='version_info.txt',     # company/product/version metadata (reduces bare-PE signal)
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name='ProxyForce',       # → dist\ProxyForce\  (zip this folder for distribution)
)
