# -*- mode: python ; coding: utf-8 -*-
# ProxyForce v3 - ONEDIR build spec, shared by the Windows and Linux builds.
# Output: dist/ProxyForce/  (folder — zip and distribute the whole folder)
#
# ONE SPEC, NOT TWO. The two builds differ only in the engine binary's name, the
# Windows-only PE decorations (manifest, icon, version resource) and a couple of
# hidden imports. Everything that matters — the onedir layout core/updater.py
# swaps, the bundled CA assets, the customtkinter data files — is identical, and
# a second spec file would drift from this one the first time either changed.
#
# WHY ONEDIR (not onefile):
# PyInstaller onefile self-extracts all bundled files (including the bundled
# sing-box binary and libcronet.dll) to a temp directory at every launch.
# Windows Defender's ML engine (Sabsik.TE.A!ml) flags this as "dropper" behaviour:
# an unsigned exe unpacking a 43 MB PE + large native DLL to disk looks exactly
# like a dropper/trojan. The detection is a false positive but Defender quarantines
# the exe before it can run.
#
# ONEDIR keeps the engine in dist/ProxyForce/_internal/singbox/ on disk from the
# moment the user extracts the zip. No runtime self-extraction happens; Defender
# sees a normal folder of files, not a dropper. This eliminates the single largest
# ML trigger. It is kept on Linux too — not for AV reasons, which do not apply
# there, but because core/updater.py's swap-the-directory design depends on the
# layout being the same on both platforms.
#
# Additional hardening (Windows):
#   • Version resource + company/product metadata embedded via version_info.txt
#     (unsigned bare PEs with no metadata score higher on suspicion).
#   • Application icon embedded (assets/proxyforce.ico, generated by tools/make_assets.py).
#   • PyInstaller bootloader rebuilt from source in CI so the exe stub doesn't carry
#     the identical hash of the PyInstaller pip wheel's prebuilt bootloader.
#   • asInvoker manifest + ShellExecuteW self-elevation retained from v2.0.2
#     (requireAdministrator manifests trigger Defender's aggressive scan path).
#
# Distribution: dist/ProxyForce/ is zipped by CI and published as the release asset,
# as ProxyForce-<tag>-win64.zip or ProxyForce-<tag>-linux64.zip. core/updater.py
# picks the right one for the platform it is running on.
#   Windows users: download zip → extract anywhere → run ProxyForce.exe → approve UAC.
#   Linux users:   download zip → extract → sudo ./packaging/install.sh (or run
#                  ./ProxyForce directly with sudo).
# The folder must stay together (the executable needs its _internal/ sibling).
#
# _find_singbox_exe() in core/singbox_controller.py already resolves the onedir
# layout on both platforms: candidate #2 is <exedir>/_internal/singbox/<engine>.
#
# Build command:
#   python tools/make_assets.py          # generate assets/proxyforce.ico
#   python -m PyInstaller proxyforce_onefile.spec --clean --noconfirm

import os
import sys

from PyInstaller.utils.hooks import collect_data_files

block_cipher = None

IS_WINDOWS = sys.platform == "win32"
_ENGINE = "sing-box.exe" if IS_WINDOWS else "sing-box"

# customtkinter ships theme JSON + image assets.
_ctk_data = collect_data_files("customtkinter")

# The packet engine: the sing-box binary plus, on Windows, libcronet.dll and the
# wintun driver it embeds. The glob takes whatever vendor/singbox holds for this
# platform; CI fetches the matching build before running PyInstaller.
_singbox_data = [('vendor/singbox/*', 'singbox')]
if not os.path.isfile(os.path.join('vendor', 'singbox', _ENGINE)):
    print(f"\n[!] vendor/singbox/{_ENGINE} is missing — fetch it before building.\n")

# Platform-specific hidden imports. PyInstaller's analysis cannot see either set:
# the Windows ones are reached through lazy `import winreg` inside functions, and
# pystray picks its backend at runtime by probing the session.
if IS_WINDOWS:
    _platform_hidden = [
        'winreg',
        'ctypes.wintypes',
        'pystray._win32',
    ]
else:
    _platform_hidden = [
        'pwd',                      # core/env_store, core/java_trust: real users
        'fcntl',                    # core/hostos: the single-instance flock
        # pystray probes these in order and uses whichever the session supports;
        # bundling all three is what lets one build work on GNOME, KDE and X11.
        'pystray._appindicator',
        'pystray._gtk',
        'pystray._xorg',
    ]

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        # sing-box binary + supporting files (placed in _internal/singbox/ in onedir).
        # CA assets: the public-trust baseline + the shipped corporate
        # inspection CA (core/env_certs). Without these the TLS-inspection
        # feature fails closed and the env vars are never written.
        ('assets/ca/*.pem', 'ca'),
        # The PNG the Linux .desktop entry points at. Bundled on both platforms so
        # the two builds come out of one spec with no conditional data list; on
        # Windows the icon is embedded in the PE and this copy is simply unused.
        ('assets/proxyforce.png', '.'),
    ] + _singbox_data + _ctk_data,
    hiddenimports=[
        # core modules (imported lazily in engine control path)
        'core.singbox_controller',
        'core.config_store',
        'core.system_proxy',
        'core.env_proxy',
        'core.env_certs',
        'core.env_store',
        'core.java_trust',
        'core.local_proxy',
        'core.hostos',
        'core.netprobe',
        'core.appcontainer',
        'core.ncsi',
        # auto-updater (lazily imported in main.py for --apply-update)
        'core.updater',
        'core._version',
        'core._ed25519',
        'hashlib',
        'zipfile',
        'urllib.parse',
        'datetime',
        # GUI framework
        'customtkinter',
        # System tray
        'pystray',
        # Pillow (tray icon + CTk image support)
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        # Clash-API stats client
        'urllib.request',
        'http.client',
        'email',
        'ctypes',
        # stdlib used at runtime
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'queue',
        'ipaddress',
        'base64',
        'select',
        'signal',
        'socket',
        'threading',
        'logging',
        'subprocess',
        'shutil',
        'importlib.util',
        'math',
        're',
    ] + _platform_hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Trim fat — none of these are used.
        'matplotlib', 'numpy', 'scipy', 'pandas',
        'html', 'xml',
        'unittest', 'pydoc', 'doctest',
        # pywin32 removed (no Windows service in v2.0)
        'win32service', 'win32serviceutil', 'win32event',
        'servicemanager', 'win32timezone', 'pywintypes',
        'pythoncom', 'win32api',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ── UAC manifest: asInvoker (self-elevation via ShellExecuteW in main.py) ────
# WHY asInvoker (not requireAdministrator):
# On Windows 10, embedding "requireAdministrator" in the manifest causes Defender
# to apply its most aggressive real-time scanning to unsigned exes from the internet.
# Solution: ship the exe as asInvoker, then main.py calls ShellExecuteW("runas")
# to re-launch itself elevated. The UAC prompt still appears; just triggered by code.
#
# The Linux counterpart is the polkit policy in packaging/linux/, which is what
# lets core/hostos.relaunch_elevated() raise a pkexec prompt instead. Neither is
# embedded in the binary there — an ELF has no manifest — so it is installed by
# packaging/linux/install.sh.
_GUI_MANIFEST = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!-- Windows 10 / 11 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
    </application>
  </compatibility>
</assembly>'''

# PyInstaller rejects manifest/icon/version/uac_admin on a non-Windows target, so
# they are passed only where they mean something.
_windows_only = dict(
    uac_admin=False,                # Self-elevation via ShellExecuteW in main.py
    manifest=_GUI_MANIFEST,
    icon='assets/proxyforce.ico',   # generated by: python tools/make_assets.py
    version='version_info.txt',     # company/product metadata (reduces bare-PE signal)
) if IS_WINDOWS else {}

# ── ONEDIR: exe stub + all assets in dist/ProxyForce/ ───────────────────────
exe = EXE(
    pyz,
    a.scripts,
    [],                      # binaries/datas go into _internal/ via COLLECT, not the stub
    exclude_binaries=True,   # onedir mode
    name='ProxyForce',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,               # OFF: UPX-packed exes trigger AV/SmartScreen.
    # No console window. On Linux this makes the binary detach from the terminal
    # the same way; --headless still logs to stdout because main.py adds a stream
    # handler for that mode explicitly.
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    **_windows_only
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name='ProxyForce',       # → dist/ProxyForce/  (zip this folder for distribution)
)
